import json
import os
from datetime import datetime, timezone


def generate_html_report(findings, target, template=None):
    safe_name = target.replace("https://", "").replace("http://", "").replace("/", "_")
    html = [
        "<!DOCTYPE html><html><head><meta charset='utf-8'>",
        "<title>Argus Security Report</title>",
        "<style>",
        "body{background:#0e1117;color:#ccc;font-family:'Courier New',monospace;padding:30px;max-width:960px;margin:auto;}",
        "h1{color:#00ff41;border-bottom:2px solid #00ff41;padding-bottom:10px;}",
        "h2{color:#00ff41;margin-top:30px;}",
        "table{border-collapse:collapse;width:100%;margin:15px 0;}",
        "th,td{padding:10px;text-align:left;border-bottom:1px solid #333;}",
        "th{background:#1a1d24;color:#00ff41;}",
        ".critical{color:#ff4444;font-weight:bold;}",
        ".high{color:#ffaa00;font-weight:bold;}",
        ".medium{color:#ffff00;}",
        ".low{color:#44ff44;}",
        ".info{color:#888;}",
        ".summary-card{background:#1a1d24;padding:20px;border-radius:8px;margin:15px 0;border-left:4px solid #00ff41;}",
        ".footer{text-align:center;color:#555;margin-top:50px;font-size:0.8rem;}",
        "</style></head><body>",
        f"<h1>:shield: Argus Security Report</h1>",
        f"<p><strong>Target:</strong> {target}</p>",
        f"<p><strong>Generated:</strong> {datetime.now(timezone.utc).isoformat()}</p>",
        f"<p><strong>Report ID:</strong> ARGUS-{datetime.now():%Y%m%d-%H%M%S}</p>",
    ]

    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        sev = f.get("severity", "info").lower()
        if sev in severity_counts:
            severity_counts[sev] += 1

    html.append("<h2>Executive Summary</h2>")
    html.append(f"<div class='summary-card'>")
    html.append(f"<p>Total Findings: <strong>{len(findings)}</strong></p>")
    html.append(f"<p>Critical: <strong class='critical'>{severity_counts['critical']}</strong> | "
                f"High: <strong class='high'>{severity_counts['high']}</strong> | "
                f"Medium: <strong class='medium'>{severity_counts['medium']}</strong> | "
                f"Low: <strong class='low'>{severity_counts['low']}</strong></p>")
    html.append("</div>")

    html.append("<h2>Findings Detail</h2>")
    if findings:
        html.append("<table><tr><th>Severity</th><th>Type</th><th>Summary</th></tr>")
        for f in findings:
            sev = f.get("severity", "info").lower()
            html.append(
                f"<tr><td class='{sev}'>[{sev.upper()}]</td>"
                f"<td>{f.get('type', '?')}</td>"
                f"<td>{f.get('summary', '?')}</td></tr>"
            )
        html.append("</table>")
    else:
        html.append("<p>No findings recorded.</p>")

    html.append("<h2>Technical Details</h2>")
    html.append(f"<pre style='background:#1a1d24;padding:15px;border-radius:4px;overflow:auto;'>{json.dumps(findings, indent=2, default=str)}</pre>")

    html.append("<div class='footer'>")
    html.append("Generated by Argus Security Framework | Confidential")
    html.append("</div></body></html>")
    return "\n".join(html)


def generate_markdown_report(findings, target):
    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        sev = f.get("severity", "info").lower()
        if sev in severity_counts:
            severity_counts[sev] += 1

    lines = [
        f"# Argus Security Report",
        f"",
        f"**Target**: {target}",
        f"**Generated**: {datetime.now(timezone.utc).isoformat()}",
        f"",
        f"## Executive Summary",
        f"",
        f"| Severity | Count |",
        f"|----------|-------|",
    ]
    for sev in ["critical", "high", "medium", "low", "info"]:
        if severity_counts[sev] > 0:
            lines.append(f"| {sev.title()} | {severity_counts[sev]} |")
    lines.extend([
        f"",
        f"**Total Findings**: {len(findings)}",
        f"",
        f"## Findings",
        f"",
    ])
    for f in findings:
        sev = f.get("severity", "info").upper()
        ftype = f.get("type", "?")
        summary = f.get("summary", "?")
        lines.append(f"- **[{sev}]** {ftype}: {summary}")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"*Generated by Argus Security Framework*")
    return "\n".join(lines)


def generate_json_report(findings, target):
    report = {
        "report_type": "Argus Security Assessment",
        "target": target,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "findings_count": len(findings),
        "findings": findings,
        "metadata": {
            "framework": "Argus Security Framework",
            "version": "2.0.0",
        },
    }
    return json.dumps(report, indent=2, default=str)


def get_available_templates():
    templates_dir = os.path.join(os.path.dirname(__file__), "..", "templates", "reports")
    if os.path.exists(templates_dir):
        return [f for f in os.listdir(templates_dir) if f.endswith(".html")]
    return ["default.html"]
