from typing import Any

from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel


class ReportParsingService:
    """
    Service responsible for parsing and normalizing agent responses.

    This class wraps LangChain's PydanticOutputParser and provides a clean
    interface for converting the agent's raw final answer into a validated
    Pydantic model.

    Responsibilities:
        - Generate format instructions for the agent prompt.
        - Parse the final agent output into the expected schema.
        - Return a safe fallback response when parsing fails.

    Keeping this logic in a dedicated service prevents parsing and validation
    concerns from leaking into the main agent orchestration layer.
    """

    def __init__(self, schema: type[BaseModel]):
        """
        Initialize the parsing service with a Pydantic schema.

        Args:
            schema:
                The Pydantic model class used to validate and structure
                the final agent output.
        """

        # Create a LangChain parser that validates output against the provided schema.
        self.output_parser = PydanticOutputParser(
            pydantic_object=schema,
        )

    def format_instructions(self) -> str:
        """
        Return formatting instructions generated from the Pydantic schema.

        These instructions can be injected into the agent prompt to guide the
        language model toward producing valid structured output.

        Returns:
            str:
                Schema-aware formatting instructions for the agent.
        """

        return self.output_parser.get_format_instructions()

    def parse_agent_result(
        self,
        raw_result: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Parse and normalize the raw result returned by the agent executor.

        The agent is expected to return a dictionary containing an "output"
        field. This method attempts to parse that output using the configured
        Pydantic parser.

        If parsing succeeds, the method returns:
            - output: validated structured data as a dictionary.
            - raw: original raw output string.

        If parsing fails, the method returns:
            - output: unparsed output if available.
            - raw: full raw agent result.
            - parsing_error: error message for debugging.

        Args:
            raw_result:
                Raw dictionary returned by LangChain's AgentExecutor.

        Returns:
            dict[str, Any]:
                Normalized response containing either parsed structured output
                or a safe fallback with parsing error details.
        """

        try:
            # Extract the final answer generated by the agent.
            raw_output = raw_result["output"]

            # Validate and parse the raw output against the configured Pydantic schema.
            parsed_report = self.output_parser.parse(raw_output)

            # Return both the structured result and the original raw model output.
            return {
                "output": parsed_report.model_dump(),
                "raw": raw_output,
            }

        except Exception as error:
            # Return a safe fallback instead of raising an exception.
            # This keeps the application stable even when the LLM returns
            # malformed JSON or output that does not match the schema.
            return {
                "output": raw_result.get("output"),
                "raw": raw_result,
                "parsing_error": str(error),
            }