from typing import List, Optional

from pydantic import BaseModel, Field


class Finding(BaseModel):
    """
    Represents a single security finding discovered during analysis.

    Each finding describes one technical issue, observation, or vulnerability
    related to a specific target such as a domain, subdomain, IP address,
    service, or web application endpoint.
    """

    target: str = Field(
        description="The specific subdomain, domain, IP address, or asset being analyzed."
    )

    issue: str = Field(
        description="The identified security issue, vulnerability, or technical observation."
    )

    severity: str = Field(
        description="Severity level of the finding. Expected values: Low, Medium, High, Critical."
    )

    description: str = Field(
        description="Detailed technical explanation of the finding, including evidence and impact."
    )

    suggested_payload: Optional[str] = Field(
        default=None,
        description=(
            "Optional sample test payload or exploit methodology, "
            "for example from PayloadsAllTheThings."
        ),
    )

    remediation: str = Field(
        description="Step-by-step remediation guidance to fix or reduce the risk."
    )


class SecurityReport(BaseModel):
    """
    Represents the final structured security report generated by Argus AI.

    This schema defines the expected output format for the agent. It is used by
    the output parser to validate that the final response contains the required
    report sections and follows a consistent structure.
    """

    summary: str = Field(
        description="High-level executive summary of the overall security posture."
    )

    attack_surface_stats: str = Field(
        description="Summary of discovered subdomains, exposed services, ports, and technologies."
    )

    findings: List[Finding] = Field(
        description="List of specific technical security findings discovered during analysis."
    )

    overall_risk_score: int = Field(
        ge=1,
        le=10,
        description="Overall risk score from 1 to 10, where 10 represents the highest risk.",
    )

    next_steps: List[str] = Field(
        description="Recommended follow-up actions for deeper testing, validation, or remediation."
    )

    output: Optional[str] = Field(
        default=None,
        description="Optional full professional Markdown report for human-readable presentation.",
    )